# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: NuGet/setup-nuget@v1.1.1
      with:
           nuget-api-key: ${{secrets.NUGET_SECRET}}
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build solution and generate NuGet package
      run: dotnet pack ./EFSorter/EFSorter.csproj -c Release -o out
    - name: Push generated package to GitHub registry
      run: dotnet nuget push /out/*.nupkg --skip-duplicate --no-symbols -k ${{secrets.NUGET_SECRET}} -s https://api.nuget.org/v3/index.json true
